title: Johannes Casera Portfolio
#logo: /assets/img/logo.png
description: Have a look at my Data Analysis Projects.
#show_downloads: true
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
